name: redux_saga
maintainer: Bilal Uslu (@bilaluslu)
description: redux_saga is a library that aims to make application side effects easier to manage, more efficient to execute, easy to test, and better at handling failures.
homepage: https://github.com/reduxsaga/redux_saga
version: 1.0.4
repository: https://github.com/reduxsaga/redux_saga

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  redux: ^4.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.0.0
  fake_async: ^1.1.0
